repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 	  "v0.11.0.1"
    hooks:
      - id: shellcheck
        args: [--severity=warning]
        files: \.(sh|bash)$
        exclude: ^$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
